[main]
font=monospace:size=12
pad=5x5

[cursor]
style=beam
blink=yes

[colors]
alpha=1.0

# nordfox
background=2e3440
foreground=cdcecf

# normal
regular0=3b4252
regular1=bf616a
regular2=a3be8c
regular3=ebcb8b
regular4=81a1c1
regular5=b48ead
regular6=88c0d0
regular7=e5e9f0

# bright
bright0=465780
bright1=d06f79
bright2=b1d196
bright3=f0d399
bright4=8cafd2
bright5=c895bf
bright6=93ccdc
bright7=e7ecf4

#[colors]
#alpha=0.98
#foreground=ebdbb2
#foreground=c0caf5
#background=1a1b26
#regular0=15161e
#regular1=f7768e
#regular2=9ece6a
#regular3=e0af68
#regular4=7aa2f7
#regular5=bb9af7
#regular6=7dcfff
#regular7=a9b1d6
#bright0=414868
#bright1=f7768e
#bright2=9ece6a
#bright3=e0af68
#bright4=7aa2f7
#bright5=bb9af7
#bright6=7dcfff
#bright7=c0caf5
